[package]
name = "backend"
version = "0.1.0"
edition.workspace = true

[dependencies]
actix-web.workspace = true
actix-files.workspace = true
sqlx.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
